
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iswwsvsnjrlxrncqitkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzd3dzdnNuanJseHJuY3FpdGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTQ3MTksImV4cCI6MjA2MzI3MDcxOX0.nkmT4ULULDbg6jN_teWDg6pRmsZRnjeN4UiryuHjVS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const sendContactMessage = async (name: string, email: string, message: string, subject: string) => {
  try {
    const { data, error } = await supabase.functions.invoke('send-contact-email', {
      body: { name, email, message, subject },
    });
    
    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error sending contact message:', error);
    return { data: null, error };
  }
};
